# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = ENV['aegir_box'].split.first
  config.vm.box_url = ENV['aegir_box'].split.last

  config.vm.host_name = "aegir.test"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "tests/functional_tests/matrix.deb"
    puppet.manifest_file = "nodes.pp"
    puppet.module_path = [ "tests/functional_tests/matrix.deb/modules" ]
    puppet.facter = {
        'aegir_api'        => ENV['aegir_api'],
        'drush_api'        => ENV['drush_api'],
        'aegir_dist'       => ENV['aegir_dist'],
        'aegir_web_server' => ENV['aegir_web_server'],
    }
  end

  # We can speed up subsequent rebuilds by caching the apt cache directories
  # on the host machine.
  config.vm.share_folder("apt_cache", "/var/cache/apt/archives", "tmp/apt/cache", :create => true)

end
