# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "deb http://debian.aegirproject.org unstable main" | sudo tee -a /etc/apt/sources.list.d/aegir-unstable.list
curl http://debian.aegirproject.org/key.asc | sudo apt-key add -
sudo apt-get update
echo "debconf debconf/frontend select Noninteractive" | debconf-set-selections
#echo "debconf debconf/priority select critical" | debconf-set-selections


# From preseedmysqlpass.sh
rootpw=$(grep password /etc/mysql/debian.cnf | head -n1 | sed -e 's/^[^=]*= *\(.*\) */\1/')
debconf-set-selections <<EOF
aegir3-hostmaster aegir/db_password string $rootpw
aegir3-hostmaster aegir/db_password seen  true
aegir3-hostmaster aegir/db_user string debian-sys-maint
aegir3-hostmaster aegir/db_host string  localhost
aegir3-hostmaster aegir/email string  aegir@example.com
aegir3-hostmaster aegir/site  string  aegir.example.com
postfix postfix/main_mailer_type select Local only

EOF

sudo DPKG_DEBUG=developer apt-get install --yes aegir3 mysql-server

SCRIPT

Vagrant::Config.run do |config|
  config.vm.box = "debian/jessie64"

  config.vm.host_name = "aegir3-deb-unstable-no-puppet.test"

  config.vm.provision "shell", inline: $script

  # We can speed up subsequent rebuilds by caching the apt cache directories
  # on the host machine.
  config.vm.share_folder("apt_cache", "/var/cache/apt/archives", "tmp/apt/cache", :create => true)

end
