# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_url = "https://atlas.hashicorp.com/debian/jessie64"

  config.vm.host_name = "aegir3-drush-master-dev.test"

  config.vm.provision "shell", inline: "apt-get update; apt-get install --yes puppet"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "tests/functional_tests/aegir3-drush-master-dev"
    puppet.manifest_file = "nodes.pp"
    puppet.module_path = [ "tests/functional_tests/aegir3-drush-master-dev/modules" ]
    puppet.facter = {
      'fqdn' => 'aegir3-drush-master-dev.test'
    }
  end

  # We can speed up subsequent rebuilds by caching the apt cache directories
  # on the host machine.
  config.vm.share_folder("apt_cache", "/var/cache/apt/archives", "tmp/apt/cache", :create => true)

  # Setup host machine cache for /var/aegir/.drush/cache.
  # The aegir user does not exist on vm creation, so using the vagrant user and 777 permissions.
  config.vm.share_folder("drush_cache", "/var/aegir/.drush/cache", "tmp/drush/cache",
      owner: "vagrant",
      group: "vagrant",
      mount_options: ["dmode=0777","fmode=0777"],
      create: true)

end
